exec-once = $HOME/Nobara_FF_UI/bin/ui-start

# notifications
exec-once = dunst &

# bluetooth applet
exec-once = blueman-applet &

# network applet
exec-once = nm-applet &

# polkit
exec-once = /usr/lib/polkit-kde-authentication-agent-1 &