# =========================
# MONITORS
# =========================
source = ~/Nobara_FF_UI/hypr/monitors.conf

# =========================
# THEME
# =========================
source = ~/Nobara_FF_UI/hypr/theme.conf

# =========================
# ANIMATIONS
# =========================
source = ~/Nobara_FF_UI/hypr/animations.conf

# =========================
# WINDOWS
# =========================
source = ~/Nobara_FF_UI/hypr/windows.conf

# =========================
# KEYBINDS
# =========================
source = ~/Nobara_FF_UI/hypr/keybinds.conf

# =========================
# AUTOSTART
# =========================
source = ~/Nobara_FF_UI/hypr/autostart.conf