$mainMod = SUPER

bind = $mainMod, RETURN, exec, kitty
bind = $mainMod, Q, killactive
bind = $mainMod, E, exec, dolphin
bind = $mainMod, D, exec, rofi -show drun

# wallpaper
bind = $mainMod SHIFT, W, exec, wallpaper-random

# discord
bind = $mainMod, C, exec, launch-discord

# browser
bind = $mainMod, B, exec, launch-browser

# steam
bind = $mainMod, S, exec, launch-steam

# HUD toggle
bind = $mainMod SHIFT, H, exec, hud-toggle

# restart waybar
bind = $mainMod SHIFT, R, exec, restart-waybar