general {
    gaps_in = 5
    gaps_out = 10

    border_size = 2

    col.active_border = rgba(aa2222ff)
    col.inactive_border = rgba(222222aa)

    layout = dwindle
}

decoration {
    rounding = 12

    blur {
        enabled = true
        size = 8
        passes = 2
    }

    drop_shadow = true
    shadow_range = 20
    shadow_render_power = 3
}

misc {
    disable_hyprland_logo = true
}